### ISSUE TITLE
deb包

### ISSUE THREAD

**Issue by jingle0927** [linuxflyos/flyos-topbar#2]
[topbar.zip](https://github.com/linuxflyos/flyos-topbar/files/1168638/topbar.zip)

期待功能强大起来。

**Comment by 1377195627** [comment]
最终样子大概就是mac的样子，全局菜单除外，但功能比mac强大

**Comment by PikachuHy** [comment]
我没太懂这个deb包的意思，如果是指我这个项目的deb包的话，
我自己能在本地打包，目前还不会怎么在github的release上放deb包。
等我再学习一下，就能放deb包了。

**Comment by chuntaojun** [comment]
有没有考虑过应用最大化和应用标题栏结合起来？因为现在好像两个额头

**Comment by 1377195627** [comment]
@chuntaojun 不喜欢最大化等整合上去，简直反人类好不，我最小化等只要在窗口上点，在标题栏上还要将鼠标移动到上面，麻烦，小屏幕还好，大屏幕就，，，，，而且大概需要改窗管实现

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by 1377195627** [comment]
@chuntaojun 你说的最大化窗口的时候，窗口的标题栏跟顶栏整合？

**Comment by imzf** [comment]
@1377195627 应该指的是类似gnome-shell-extension-pixel-saver这样的gnome插件，支持最大化后隐藏标题栏，从顶栏往下拖动，恢复原状。我个人非常喜欢这种效果，节约空间又美观，不过我不喜欢某些插件会把最大化最小化按钮也集成到顶栏，丑而且占用空间。

**Comment by 1377195627** [comment]
@imzf 最大化后隐藏标题栏，从顶栏往下拖动，恢复原状.
如果是手机，下拉毫无违和感，要是电脑用鼠标就............，而且系统托盘也在上面，隐藏了那就不方便了，而且网速显示也在上面，隐藏了，还有什么用，开浏览器，肯定是全屏的，开个视频网站，看看网速还要下拉？

**Comment by imzf** [comment]
@1377195627 一般都会更习惯拖动窗口到边缘最大化的吧，而且也不影响看网速音乐控制啥的啥的啊
![l](https://user-images.githubusercontent.com/3401994/30373206-21992184-9846-11e7-891f-2d5c580c80d3.gif)

**Comment by 1377195627** [comment]
@imzf 你说的隐藏topbar........
